on: [push, pull_request]

name: Continuous integration

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake -B build -S .
          cmake --build build --target clang-format-check
  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake -B build -S .
          cmake --build build
